packages:
  - packages/*

allowBuilds:
  esbuild: true
  puppeteer: true
  snyk: true

overrides:
  'brace-expansion@^5': '^5.0.8'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
linkWorkspacePackages: true
verifyDepsBeforeRun: false
