packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - puppeteer

overrides:
  'qs@^6.0.0': '^6.14.1'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

linkWorkspacePackages: true
preferFrozenLockfile: true
shamefullyHoist: true
shellEmulator: true
