version: 2.1

parameters:
  isNightly:
    type: boolean
    default: false

commands:
  prepare_environment_command:
    description: "Prepare environment (RAM, browsers, hosts, etc.)"
    steps:
      # CircleCI does not use the latest Chrome. Hence, we must install it manually.
      - run:
          name: Install the latest Chrome
          command: yarn ckeditor5-dev-ci-install-latest-chrome

  bootstrap_repository_command:
    description: "Bootstrap the repository"
    steps:
      - install_ssh_keys_command
      - run:
          name: Install dependencies
          command: yarn install

  install_ssh_keys_command:
    description: "Install SSH keys"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a0:41:a2:56:c8:7d:3f:29:41:d1:87:92:fd:50:2b:6b"

jobs:
  notify_ci_failure:
    machine: true
    parameters:
      hideAuthor:
        type: string
        default: "false"
    steps:
      - checkout
      - bootstrap_repository_command
      - run:
          # In the PRs that comes from forked repositories, we do not share secret variables.
          # Hence, some of the scripts will not be executed.
          name: 👤 Verify if the build was triggered by community - Check if the build should continue
          command: |
            #!/bin/bash

            if [[ -z ${COVERALLS_REPO_TOKEN} ]];
            then
              circleci-agent step halt
            fi
      - run:
          environment:
            CKE5_SLACK_NOTIFY_HIDE_AUTHOR: << parameters.hideAuthor >>
            CKE5_PIPELINE_NUMBER: << pipeline.number >>
          name: Waiting for other jobs to finish and sending notification on failure
          command: yarn ckeditor5-dev-ci-circle-workflow-notifier
          no_output_timeout: 1h

  main:
    machine: true
    environment:
      # To address the "error:0308010C:digital envelope routines::unsupported" issue.
      NODE_OPTIONS: --openssl-legacy-provider
    steps:
      - checkout
      - bootstrap_repository_command
      - prepare_environment_command
      - run:
          name: Execute ESLint
          command: yarn run lint
      - run:
          name: Run unit tests
          command: yarn run coverage
      - run:
          name: Verify build (JavaScript, npm)
          command: node scripts/ci/verify-build -l js -p npm
      - run:
          name: Verify build (JavaScript, yarn)
          command: node scripts/ci/verify-build -l js -p yarn
      - run:
          name: Verify build (JavaScript, npm, legacy)
          command: node scripts/ci/verify-build -l js -p npm -m
      - run:
          name: Verify build (JavaScript, yarn, legacy)
          command: node scripts/ci/verify-build -l js -p yarn -m
      - run:
          name: Verify build (TypeScript, npm, custom plugin name)
          command: node scripts/ci/verify-build -l ts -p npm -n CustomPluginName
      - run:
          name: Verify build (TypeScript, npm, legacy, custom plugin name)
          command: node scripts/ci/verify-build -l ts -p npm -m -n CustomPluginName
      - run:
          name: Verify build (JavaScript, yarn, custom plugin name)
          command: node scripts/ci/verify-build -l js -p yarn -n customPluginName400
      - run:
          name: Verify build (JavaScript, yarn, legacy, custom plugin name)
          command: node scripts/ci/verify-build -l js -p yarn -m -n customPluginName400
      - run:
          name: Verify build (TypeScript, yarn)
          command: node scripts/ci/verify-build -l ts -p yarn
      - run:
          name: Verify build (TypeScript, yarn, legacy)
          command: node scripts/ci/verify-build -l ts -p yarn -m
      - unless:
          # Upload the code coverage results for non-nightly builds only.
          condition: << pipeline.parameters.isNightly >>
          steps:
            - run:
                # In the PRs that comes from forked repositories, we do not share secret variables.
                # Hence, some of the scripts will not be executed.
                name: 👤 Verify if the build was triggered by community - Check if the build should continue
                command: |
                  #!/bin/bash

                  if [[ -z ${COVERALLS_REPO_TOKEN} ]];
                  then
                    circleci-agent step halt
                  fi
            - run:
                name: Upload code coverage
                command: cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

workflows:
  version: 2
  main:
    unless: << pipeline.parameters.isNightly >>
    jobs:
      - main
      - notify_ci_failure:
          filters:
            branches:
              only:
                - master

  nightly:
    when: << pipeline.parameters.isNightly >>
    jobs:
      - main
      - notify_ci_failure:
          hideAuthor: "true"
          filters:
            branches:
              only:
                - master
